### ISSUE TITLE
Update or change Rollup dependency version range

### ISSUE THREAD

**Issue by peterhil** [elycruz/rollup-plugin-sass#112]
When installing or updating dependencies with Pnpm, it nags with the following error since I updated to Rollup 3.17.2.

```
devDependencies:
- rollup-plugin-sass 1.12.17
+ rollup-plugin-sass 1.12.18

 WARN  Issues with peer dependencies found
.
└─┬ rollup-plugin-sass 1.12.18
  └─┬ @rollup/pluginutils 3.1.0
    └── ✕ unmet peer rollup@^1.20.0||^2.0.0: found 3.17.2
```

I bet that this plugin will not work with Rollup v1 anymore, and it seems to work with the latest Rollup versions.

Maybe change the [Rollup version range on package.json](https://github.com/elycruz/rollup-plugin-sass/blob/master/package.json#L77) to something like `^2 || ^3`? Or then something more specific – there is a [npm semantic version calculator](https://semver.npmjs.com/) by Npm.

**Comment by elycruz** [comment]
Thanks for submitting the ticket (ticket assigned).  Also - we're going to keep rollup 1.x support, for now, since some users might actually be using that version range.

**Comment by elycruz** [comment]
Update merged and published.

**Comment by elycruz** [comment]
Issue closed automatically, via pull-request lifecycle - Patch performed - Fix is now deployed at package version https://www.npmjs.com/package/rollup-plugin-sass/v/1.12.19 .
