### ISSUE TITLE
Inject the style to head tag does not work

### ISSUE THREAD

**Issue by NetanelBasal** [elycruz/rollup-plugin-sass#13]
I am trying to inject the style to the head tag, the function `___$insertStyle` is generated in the main bundle js file but no one is calling the function.

``` js
    scss({
      output: 'build/bundle.css',
      insert: true,
      options: {
        outputStyle: 'compressed'
      },
      processor(code) {
        return postcss([require('autoprefixer')])
          .process(code)
          .then((result) => {
            return result.css;
          });
      }
    }),
```

**Comment by differui** [comment]
@NetanelBasal Thanks for your reply.This bug was fixed and new version [0.4.1](https://www.npmjs.com/package/rollup-plugin-sass) was released.
