### ISSUE TITLE
feat: support *.css files by default

### ISSUE THREAD

**Issue by elycruz** [elycruz/rollup-plugin-sass#138]
Currently (with #131 ) the plugin supports `*.css` files (by adding inclusion of them (via option `include`)), however it might be cumbersome to have to specify you want to support *.css files, in given projects, due to possibly not remembering that you have to specify support for `*.css` file extension.

## Acceptance Criteria

- [ ] Add `**/*.css` in the plugins `defaultIncludes` array.
- [ ] Unit tests showing a working example.

**Comment by 08AHAD** [comment]
please assign me this issue

**Comment by elycruz** [comment]
Assigned.

**Comment by elycruz** [comment]
We're not going to attempt to support *.css to *.css compilation for now as 'dart-sass', and other sass-only compilers don't directly support css imports (`@import url('...*.css')` - We're leaving this functionality to other plugins/libraries to handle.
