### ISSUE TITLE
 this is a bug

### ISSUE THREAD

**Issue by lennylinyu** [elycruz/rollup-plugin-sass#149]
https://github.com/elycruz/rollup-plugin-sass/blob/0425739612e38ded0fda00e5060b25a735d620c3/src/index.ts#L80
This should return a promise, but it returned undefined

**Comment by lennylinyu** [comment]
If the css file has blank data, throw [!] (plugin rollup-plugin-sass) TypeError: Cannot read properties of undefined (reading 'then')

**Comment by elycruz** [comment]
Good catch!

**Comment by elycruz** [comment]
New ticket: 
#150 .

**Comment by elycruz** [comment]
Fix merged and published (see #153 ).
