### ISSUE TITLE
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by twilson90** [elycruz/rollup-plugin-sass#159]
Whenever I use rollup with this plugin I get 2 identical warnings in the output:

```
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
```

**Comment by claycarpenter** [comment]
This [warning can be silenced](https://sass-lang.com/documentation/breaking-changes/legacy-js-api/#silencing-warnings) by adding `silenceDeprecations: ['legacy-js-api']` to your `options` property.

The full `sass` call would then look something like:
```javascript
sass({
  // ...you existing configuration
  
  options: {
    silenceDeprecations: ['legacy-js-api'],
  },
})
```

This works fine for me and silences the warning until root issue can be resolved.

**Comment by twilson90** [comment]
> This [warning can be silenced](https://sass-lang.com/documentation/breaking-changes/legacy-js-api/#silencing-warnings) by adding `silenceDeprecations: ['legacy-js-api']` to your `options` property.
> 
> The full `sass` call would then look something like:
> 
> ```js
> sass({
>   // ...you existing configuration
>   
>   options: {
>     silenceDeprecations: ['legacy-js-api'],
>   },
> })
> ```
> 
> This works fine for me and silences the warning until root issue can be resolved.

Not working for me :(
