### ISSUE TITLE
Allow relative non-existent paths via "{output:'build/styles/mystyle.css, ...}'" 

### ISSUE THREAD

**Issue by git-toni** [elycruz/rollup-plugin-sass#16]
I was getting an error when configuring the plugin like:

``` javascript
let scssOpt = { 
  output: "build/mystyles/bundle.css"
}
```

Which was cause by the filepath `build/mystyes` not existing. IMHO this would be a handy feature, since many times we want JS and CSS to live in separate folders ( other than the root path of `rollup.config.js`). 

---

To achieve this I did the following:
- Added a partial dependency on the convenient `fs-extra` package; in principle it could be a replacement for `fs` altogether, but I finall left the original `fs.writeFileSync` call.
- Modified the `output-path` test slightly, to cover this case.

I hope this can be useful!

**Comment by differui** [comment]
@git-toni Thanks for this handy feature.😄 Can you help to review the comment in #17.

**Comment by git-toni** [comment]
done!
