### ISSUE TITLE
Can we get compatible options?

### ISSUE THREAD

**Issue by thgh** [elycruz/rollup-plugin-sass#3]
Compatible with [rollup-plugin-css-only](https://github.com/thgh/rollup-plugin-css-only)
### output
- Type: `String|Function|Boolean` _(default: true)_

If you specify a string, it will be the path to write the generated CSS.
If you specify a function, call it passing the generated CSS as an argument.
If you specify true, the stylesheet is placed next to the bundle: _e.g. bundle.js => bundle.css_
If you specify false, it will export the stylesheet as a string.

**Comment by differui** [comment]
It looks good.I will check that plugin later and make similar option in this one.

**Comment by differui** [comment]
@thgh 

The implementation of `output` option in this plugin will be a little different with **rollup-plugin-css-only**.The primary purpose of this plugin is import CSS into JavaScript. So `output` will be disabled by default.

### output
- Type: `String|Function|Boolean` _(default: false)_

``` js
sass({
    // Default behaviour disable output
    output: false,

    // Write all styles to the bundle destination where .js is replaced by .css
    output: true,

    // Filename to write all styles
    output: 'bundle.css',

    // Callback that will be called ongenerate with two arguments:
    // - styles: the concatentated styles in order of imported
    // - styleNodes: an array of style objects:
    //   [
    //     { id: './style1.scss', content: 'body { color: red };' },
    //     { id: './style2.scss', content: 'body { color: green };' }
    //   ]
    output(styles, styleNodes) {
        writeFileSync('bundle.css', styles);
    }
});
```
