### ISSUE TITLE
cannot compressed the css

### ISSUE THREAD

**Issue by 374632897** [elycruz/rollup-plugin-sass#31]
I used the configuration like this
```js
sass({
    output: 'dist/app.css',
    options: {
      outputStyle: 'compressed',
      sourceMap: false,
    }
 }),
```
But the dest file is not be compressed.  How can I fixed it? Thanks.

**Comment by differui** [comment]
Hi @374632897 I added a test case (#32) for this issue.It looks like can't reproduce the bug.Maybe you can do adjustments and reproduce the bug.

**Comment by 374632897** [comment]
@differui Thanks, but I still cannot get the compressed code use the way you offered in the test case.
```js
const isProd = process.env.NODE_ENV === 'prod';

function compress(str) {
  return str.trim().replace(/[\n\r\s]/g, '').replace(/;}$/, '}');
}
export default {
  entry: 'src/index.vue',
  dest: 'dist/vue-emoji.js',
  format: 'umd',
  moduleName: 'VueEmoji',
  sourceMap: !isProd,
  plugins: [
    resolve({
      jsnext: true,
      main: true,
      browser: true
    }),
    vue(),
    sass({
      output (styles) {
        fs.writeFileSync('dist/vue-emoji.css', compress(styles));
      }
      // output: 'dist/vue-emoji.css',
      // options: {
      //   outputStyle: 'compressed',
      //   sourceMap: false
      // }
    }),
    babel({
      exclude: 'node_modules/**'
    }),
    commonjs(),
    (isProd && uglify())
  ]
}
``` 
By the way , I import *.scss files in .vue components, like this
```js
<style lang = 'scss' scoped>
@import './emoji-sprite.scss';
<style>
```
Do this affect it ?

**Comment by differui** [comment]
@374632897 I think `rollup-plugin-vue` compiled everything in `.vue` files (scripts, styles and templates).Since as `rollup-plugin-sass` view there is no more `@import style from 'path/to/style.scss'` statement.

**Comment by 374632897** [comment]
@differui 突然发现是一个地方的， 就直接用中文了。。。 
![image](https://cloud.githubusercontent.com/assets/15151718/24031577/48431da4-0b1e-11e7-9569-9b32ef9f6774.png)
最后出来的是这样。 都是未压缩的， 然后我这边试了一下， 如果要是使用的是从`vue`处理过的内容的话， 那么不会被压缩， 其他的则会被正常压缩， 所以我现在有点不大明白了， 到底是哪个地方的问题。 vue的话， 我是使用的rollup-plugin-vue。

**Comment by differui** [comment]
哈哈！我觉得如果你的项目都是 `.vue` 写的话直接用 `rollup-plugin-vue` 就可以了。这个里面也是用了 `node-sass` 编译 `<style lang="sass"></style>` 的内容。具体怎么配置要看下这个插件文档。

**Comment by differui** [comment]
@374632897 看看这个有没有用：https://github.com/vuejs/rollup-plugin-vue/blob/26b6b979198f7d6844617af5412576c51f347ccc/docs/en/2.3/README.md

**Comment by 374632897** [comment]
@differui  真是太感谢了。 我在README和他提供的网站上都没有看到插件的使用说明，也没注意到目录里的docs   o(╯□╰)o  :grin:
