### ISSUE TITLE
Support passing in options.data

### ISSUE THREAD

**Issue by chiefcll** [elycruz/rollup-plugin-sass#34]
In my build process I need to add variables to sass for environment information. I did this before by

`options.data = '$sprite: \'' + host + '/sprite.png\'; \n' + sassFile`

Thus I'd like to be able to pass in {data: variables} and this plugin would do {data: options.data + code} to pass it to node-sass

**Comment by chiefcll** [comment]
You can find out more information about the problem here: 

http://stackoverflow.com/questions/31148803/injecting-variables-during-sass-compilation-with-node

**Comment by differui** [comment]
Thanks for PR.
New version [0.5.2](https://www.npmjs.com/package/rollup-plugin-sass)  published.
