### ISSUE TITLE
Using options - file of node-sass in plugin config

### ISSUE THREAD

**Issue by rjnair-nm** [elycruz/rollup-plugin-sass#41]
I have an entry.scss file which comprises of all the scss files to be imported :- I dont import entry.scss in my rollup entry js file. So thats the reason i use the file option in the plugin.

**Entry.scss**
```
@import './fonts.scss';
@import './components/App.scss';
@import './components/Navigation.scss';

```

But when i provide the file option within the plugin, it doesn't work :-

**Plugin config**
```
sass({
   options: {
      file: 'src/app/styles/entry.scss;'
    },
    output: 'build/public/bundle.css'
}),
```

**Comment by differui** [comment]
Only scss files which imported in rollup entry js file can be compiled.
