### ISSUE TITLE
You can't get the real source paths when using sourceMapEmbed

### ISSUE THREAD

**Issue by homer0** [elycruz/rollup-plugin-sass#45]
Hi,

I was trying to build a plugin that would extract images and web fonts from the generated CSS and copy them to the distribution directory.

The idea was to use `sourceMapEmbed`, then after this plugin generated the CSS, I would go get the map, list the original sources and search for `url(...)`s on the code, copy them and replace the path on the CSS.

The problem I found is that, because this plugin uses `renderSync` with the `data` option, the source map `sources` is `stdin`.

Playing around with the plugin code I saw that the only reason for using `data` is when you receive the `prependSass` option, and I was thinking that maybe you could use `data` only when `prependSass` has some value, and in case is empty, use `file`.

The change would be something like this:

```diff
- const sassConfig = Object.assign({ data: `${prependSass}${code}` }, options.options);
+ const baseConfig = prependSass
+   ? { data: `${prependSass}${code}` }
+   : { file: id };
+ const sassConfig = Object.assign(baseConfig, options.options);
```

The rest would work the same.

Would you consider it if I send a PR?
Regards

**Comment by differui** [comment]
Hi @homer0, I think it could be nice.Feel free to send the PR.I will handle it in time.

**Comment by differui** [comment]
hi @homer0  checkout the new version:

rollup-plugin-sass@0.6.1

**Comment by homer0** [comment]
@differui Awesome, thanks!!!
