### ISSUE TITLE
node10 regression

### ISSUE THREAD

**Issue by bobaaaaa** [elycruz/rollup-plugin-sass#48]
Hey,
I have a working rollup + sass setup. When updating to node10 it stoped working.

Testet envs:
✅ node `9.11.1` + rollup `0.58.2` + rollup-plugin-sass `0.6.1`
❌ node `10.0.0` + rollup `0.58.2` + rollup-plugin-sass `0.6.1`

**Comment by differui** [comment]
I've added node@10.0.0 as CI envs, [it's passed](https://travis-ci.org/differui/rollup-plugin-sass/jobs/375785598). @bobaaaaa could you show more error messages?

**Comment by bobaaaaa** [comment]
Ah nice, thanks for the fast feedback. I increased the log level. Maybe it's the TypeScript rollup plugin. I close this issue. 👍
