### ISSUE TITLE
'resolve' doesn't resolve a path for node_modules

### ISSUE THREAD

**Issue by homer0** [elycruz/rollup-plugin-sass#55]
Hi,

I'm having a weird issue: I'm using an `@import` for a package, with `~`, and `resolve` sometimes fails to resolve the path and hangs  the whole Rollup process.

I've been debugging it and the issue is in [this call](https://github.com/browserify/resolve/blob/master/lib/async.js#L8), that for some reason, sometimes doesn't invoke the callback.

At this point you may be wondering why I'm creating an issue here and not on the `resolve` repository? Well, even if the issue is with `resolve`, I thought that I can easily bypass that by adding a custom importer... but custom importers are added after the one on the plugin, so if `resolve` _"doesn't resolve"_ the path, they are never called.

Finally, the questions:

1. Do you think it would be possible to add custom importers before the one from the plugin?
2. If no, what about an option to define their priority?
3. Why do you `resolve` instead of `require.resolve`?

If you consider 1 or 2 above 3, I can make a PR.

Regards

**Comment by differui** [comment]
Hi @homer0 ,

1. Maybe we can dig the issue deeper? Can you help to reproduce it? Maybe it's another bug.
2. If no, can `require.resolve` fix it?
3. If `resolve` and `require.resolve` all failed, we use the custom importer.
4. I copy the `resolve` strategy from [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss/blob/master/src/sass-loader.js).

Thx!

**Comment by homer0** [comment]
Hi @differui 

I wanted to give you something to reproduce it, but it's kind of hard because I'm migrating a webpack application for work, and I can't share it.

But I think I found the issue! The file that imports from `node_modules` is being imported on 4 different files (is a list of variables for a "theme"). I think `resolve` hangs when called async with the same path more than once. I'll debug this theory later and let you know.

I'll test it with a _"resolution cache"_ and see how it goes.

Now, I mentioned `require.resolve` because I felt like it was weird for a Node project to be using a polyfill of a Node utility.

Btw, thanks for the fast reply!

**Comment by homer0** [comment]
Hey @differui 

Ok, I did some more debugging and I can assure you it is related to the `resolve` async functionality.

I tried adding a custom _"resolve with cache"_:

(I may look ugly, I wrote it fast just to test the theory :P)

```js
import resolve from 'resolve';

const deferred = () => {
  const result = {
    resolve: null,
    reject: null,
  };

  result.promise = new Promise((resolve, reject) => {
    result.resolve = resolve;
    result.reject = reject;
  });

  return result;
};

const cache = {};

export default (url, basedir) => {
  const key = `${url}-${basedir}`;
  let result;
  if (cache[key]) {
    result = cache[key].value ?
      Promise.resolve(cache[key].value) :
      cache[key].defer.promise;
  } else {
    cache[key] = {
      defer: deferred(),
    };

    result = cache[key].defer.promise;

    const options = {
      basedir,
      extensions: ['.scss', '.sass'],
    };

    resolve(url, options, (error, value) => {
      const resolved = error ? url : value;
      cache[key].defer.resolve(resolved);
      cache[key].value = resolved;
      delete cache[key].defer;
    });
  }

  return result;
};
```

But this didn't work either; `resolve` never invoked the callback, even if it was just one call.

Now, the reason I can assure the issue is related to the async functionality is because if I change resolve to `sync`, it works:

```diff
- pify(resolve)(moduleUrl, resolveOptions).then(function (id) {
-   return done({ file: id });
- }).catch(function () {
-   return done({ file: url });
- });
+ let resolved;
+ try {
+   resolved = resolve.sync(moduleUrl, resolveOptions);
+ } catch (error) {
+   resolved = url;
+ }
+ return done({ file: resolved });
```

Finally, here's kind of the structure I'm working with in case you get an idea: I have a `variables.scss` that imports another variables file from `node_modules`, and then I have ~20 AngularJS components importing their own stylesheets, the ones importing `variables.scss`.

Let me know what you think!

**Comment by differui** [comment]
@homer0 I made a new version with sync `resolve`: [rollup-plugin-sass@0.8.1](https://github.com/differui/rollup-plugin-sass/releases/tag/0.8.1) hope that fix your problem.
BYW, thank you for the bug report!

**Comment by homer0** [comment]
@differui It works perfectly :D 

Thank you so much for the help!!!
