### ISSUE TITLE
Consider switching to sass from node-sass

### ISSUE THREAD

**Issue by TheBosZ** [elycruz/rollup-plugin-sass#56]
Since #54 has been merged and individual projects can choose which run time to use, it would be nice to switch the default from node-sass to sass.

Speed-wise, they seem to be about the same (according to the tests here: https://github.com/sass/dart-sass/blob/master/perf.md) and installing node-sass is always a pain.

For users who truly need node-sass, they can include it manually.

**Comment by differui** [comment]
Hi @TheBosZ you are right. #54 only add `runtime` option but have not remove `node-sass` from `dependiences` we should install `node-sass` as before.

Thanks for the advice. I will switch to sass from node-sass.

**Comment by differui** [comment]
new version [0.9.0](https://github.com/differui/rollup-plugin-sass/releases/tag/0.9.0)
