### ISSUE TITLE
When resolve.sync fails the catch clause prevents any custom importer from running

### ISSUE THREAD

**Issue by kentaromiura** [elycruz/rollup-plugin-sass#58]
https://github.com/differui/rollup-plugin-sass/blob/e94b639f895563b9f78bb53c21695ce02fe0a56a/src/index.js#L69-L73
this logic prevents any custom importer from running, a better way is to return null in case `customizedSassOptions.importer` is defined to allow it/them to run.

To reproduce just try to import with any custom path format that will not correctly resolve for example a path with a variable like:
```
@import '~test/${theme}/utils';
```
it will fail and notice that even after adding
```
options: {
        importer: [
          function(url, prev, done) {
            console.log('this will never run...');
          }
        ],
       // ...
}
```
The custom importer doesn't run (while it does after returning `null`).

**Comment by differui** [comment]
Please retry the latest version [0.9.3](https://www.npmjs.com/package/rollup-plugin-sass/v/0.9.3) the bug shoud be fixed. Have a nice day :)
