### ISSUE TITLE
Update for rollup 1.0

### ISSUE THREAD

**Issue by dekdevy** [elycruz/rollup-plugin-sass#61]
just a heads up, as of rollup 1.0, this plugin throws a deprecation warning.

`(!) sass plugin: The ongenerate hook used by plugin sass is deprecated. The generateBundle hook should be used instead.`

**Comment by differui** [comment]
It's fixed from [rollup-plugin-sass@1.0.1](https://www.npmjs.com/package/rollup-plugin-sass/v/1.0.1).

**Comment by differui** [comment]
Hi @dekdevy. Thanks for reporting the bug. Use the latest version [rollup-plugin-sass@1.1.0](https://www.npmjs.com/package/rollup-plugin-sass/v/1.1.0).

**Comment by dekdevy** [comment]
Thanks, working well. I appreciate your quick response and nice plugin.

**Comment by differui** [comment]
😄
