### ISSUE TITLE
insert + rollup-plugin-node-resolve v5 did not work

### ISSUE THREAD

**Issue by bobaaaaa** [elycruz/rollup-plugin-sass#64]
A rollup config with sass + rollup-plugin-node-resolve@5 and the option `insert: true` did not work properly. See [Changelog](https://github.com/rollup/rollup-plugin-node-resolve/blob/master/CHANGELOG.md#500-2019-05-15).

What I can see:
- the global `___$insertStyle` function is generated correctly in the bundle
- the actual call of the `___$insertStyle` function including the styles is not generated

Here are my `rollup.config.js`:

```js
{
    input: './src/foo.ts',
    output: [
        { file: 'dist/foo.js', format: 'es' }
    ],
    external: ['bar'],
    plugins: [
        resolve(),
        typescript(),
        sass({
            output: false,
            insert: true
        })
    ]
}
```

Workaround:
Remove `rollup-plugin-node-resolve`
or
Use `rollup-plugin-node-resolve@4.2.4` (latest v4)

**Comment by differui** [comment]
[rollup-plugin-sass.test.zip](https://github.com/differui/rollup-plugin-sass/files/3189894/rollup-plugin-sass.test.zip)

Hi @bobaaaaa :

I created a simple codebase according to your description but fail to reproduce the bug.
Can you give it a look and help to reproduce?

**Comment by differui** [comment]
[rollup-plguin-sass.test.zip](https://github.com/differui/rollup-plugin-sass/files/3189877/rollup-plguin-sass.test.zip)

Hi @bobaaaaa :

I created a simple codebase according to your description and cannot reproduce the bug.
Can you give it a look and help to reproduce the bug?

**Comment by bobaaaaa** [comment]
Hi @differui you're right. I can not reproduce my problem with a clean/new project. It seems to be a problem with our strange project setup/build (yarn + monorepo + typescript. I close the issue. Sorry
