### ISSUE TITLE
Any hint on how to write hash in final file name?

### ISSUE THREAD

**Issue by frederikhors** [elycruz/rollup-plugin-sass#65]
Any hint on how to write hash in final file name?

**Comment by differui** [comment]
Use the `output: callback` option and generate a hash name from the callback parameters?

**Comment by frederikhors** [comment]
And how to "generate a hash name"?

**Comment by SKalt** [comment]
Here's how I do it (based on [rollup's own implementation](https://github.com/rollup/rollup/blob/master/src/Chunk.ts)):

```javascript
import sha256 from 'hash.js/lib/hash/sha/256'

sass({
  output: (style) => {
    const hash = sha256().update(styles).digest('hex')
    const fileName = `styles-${hash.substring(0, 8)}.css`
    mkdirSync('path/to/output/dir', {recursive: true})
    writeFileSync(`path/to/output/dir/${fileName}`, styles)
  }
})
```

**Comment by elycruz** [comment]
Moving to 'triaged' - For now the above solutions will suffice but we need to leverage rollup's existing lifecycle related config options (`output.chunkFileNames`, etc.) to achieve the same thing.  New ticket created: #122 .

**Comment by elycruz** [comment]
Closing this ticket as both rollup-plugin-sass `output: callback` and rollup's `output` options (for example `https://rollupjs.org/configuration-options/#output-chunkfilenames`) offer solutions for this.

@frederikhors I know it's like 10 years later (:D) but If you're still facing the issue please feel free to reopen the ticket.

**Comment by frederikhors** [comment]
@elycruz I breed horses today. 🤣
