### ISSUE TITLE
Why is the sass version locked to 1.7.2?

### ISSUE THREAD

**Issue by MarekLacoAXA** [elycruz/rollup-plugin-sass#67]
Why is the sass version locked to 1.7.2?
I think it would be beneficial to use never versions. Correct me if I am missing something.

I need the importing of CSS same as @LucaMele in #50 
According to the docu of SASS-LANG the sass lib supports this since 1.11.0:
https://sass-lang.com/documentation/at-rules/import#importing-css

**Comment by jderochervlk** [comment]
This would also allow us to include `@use` and `@forward`.

I'll look into making a PR to fix this.

**Comment by aarongarciah** [comment]
You can use the [`runtime`](https://github.com/differui/rollup-plugin-sass#runtime) option to pass the `sass` implementation that you want. For example, you can install in your project `sass@1.26.3` and then when using `rollup-plugin-sass` pass the option:

```javascript
sass({
  options: {
    runtime: require('sass')
  }
})
```

This way you can use `rollup-plugin-sass` with the `sass` version that your project is using.
