### ISSUE TITLE
Support for minification

### ISSUE THREAD

**Issue by tomasklim** [elycruz/rollup-plugin-sass#70]
Hello, 

I really miss minification in this plugin.

I know that there is a workaround
`
processor: isProd
        ? (css) =>
            postcss({ from: undefined, plugins: [cssnano()] })
              .process(css)
              .then((result) => result.css)
        : null,
`

but it would be better integrated :)

**Comment by eduardoumpierre** [comment]
Hello @tomasklim,

I'm not sure if it's enough for your case, but there's the [outputStyle](https://sass-lang.com/documentation/js-api/modules#OutputStyle) option in sass. You can use it like this:
```js
sass({
  output: 'dist/index.css',
  options: {
    outputStyle: isProduction ? 'compressed' : 'expanded',
  },
})
```

**Comment by elycruz** [comment]
@tomasklim cssnano, postcss etc. are external to `sass`/`node-sass` plugins so will not be integrated into this plugin;  For minification please use the 'outputStyle' option, as @EduardoUmpierre  pointed out (abovee) with appropriate value (https://sass-lang.com/documentation/js-api/interfaces/LegacySharedOptions#outputStyle), additionally you could still use postcss -> nano with your builds, as a further optimization step. 

Marking as closed as no extra actions required.
