### ISSUE TITLE
Can't use in typescript config file

### ISSUE THREAD

**Issue by SettingDust** [elycruz/rollup-plugin-sass#87]
```
(!) Cannot call a namespace ('sass')
rollup.config.ts (23:8)
21:         nodeResolve({ browser: true }),
22:         commonjs(),
23:         sass({
            ^
24:             processor: css => postcss([autoprefixer])
25:                 .process(css)
loaded rollup.config.ts with warnings
[!] TypeError: sass__namespace is not a function
```

No error in IDE. But can't compile.

Can be fixed with `"allowSyntheticDefaultImports": true` in `tsconfig.json` `compilerOptions`

According to discussion here https://github.com/rollup/rollup-plugin-commonjs/issues/157#issuecomment-284858177. It seems that can't be fixed. Please add to document

可以使用 `"allowSyntheticDefaultImports": true` in `tsconfig.json` `compilerOptions` 修复
根据 https://github.com/rollup/rollup-plugin-commonjs/issues/157#issuecomment-284858177 的讨论，看起来无法修复，需要加到文档里

**Comment by elycruz** [comment]
@SettingDust Update to docs highlighting use of `esModuleInterop`/`allowSyntheticDefaultImports`,  when using *.ts rollup config files published:
Change commit:
https://github.com/differui/rollup-plugin-sass/commit/f48080881e5f55032c2777b79d6b648605ddd4cf
On npm:  (v1.2.8)[https://www.npmjs.com/package/rollup-plugin-sass/v/1.2.8]

**Comment by elycruz** [comment]
Linked npm link (for quick access):
[v1.2.8](https://www.npmjs.com/package/rollup-plugin-sass/v/1.2.8)
