### ISSUE TITLE
No output file?

### ISSUE THREAD

**Issue by sam-s4s** [elycruz/rollup-plugin-sass#9]
I'm having trouble getting sass() to actually do anything, and I can't find any tutorials or examples anywhere to help...

```
export default {
    entry: 'app/main_jit.ts',
    dest: '../../../bin/web/billing/bundle.js',
    sourceMap: false,
    format: 'iife',
    plugins: [
        angular(),
        typescript({
            "target": "es5",
            "module": "es2015",
            "moduleResolution": "node",
            "sourceMap": false,
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
            "removeComments": false,
            "noImplicitAny": true,
            "strictNullChecks": false,
            "suppressImplicitAnyIndexErrors": true
        }),
        nodeResolve({module: true}),
        commonjs({
            include: 'node_modules/rxjs/**'
        }),
        sass({
            output: '../../../bin/web/billing/index.css',
            options: {
                file: 'app/index.scss'
            }
        })
    ]
}
```

As you can see, I'm trying to take in an scss file 'app/index.scss' and then produce a css file '../../../bin/web/billing/index.css'... however no file is ever generated.

I've tried many combinations of paths for both input and output, and I've never seen any output files at all, anywhere. What am I doing wrong?

(note: it works fine with node-sass, using the same file paths)

Also, why is there an "output" param, if there is already an outFile in the sass options?

Thanks

**Comment by differui** [comment]
Sorry for hard feeling... 😔

This plugin helps to importing `.scss` or `.sass` into `.js` rather than compiling standalone sass file outside of any `.js`.You may need other way to do this.

``` scss
// style.scss
a {
    color: red;
}
```

``` js
// index.js
import style from './style.scss';

console.log(style);
```

will yield:

``` js
// index.js
const style = 'a {\n    color: red;\n}';

console.log(style);
```

Sometimes we may not except stylesheets in our javascript files and with `output` option we can gather scattered `.scss` or `.sass` files and output into a single file.

**Comment by sam-s4s** [comment]
Oh ok, so this plugin cannot deal with scss to css without importing into js? :(

**Comment by differui** [comment]
Yes rollup only handle `*.js` file as entry.
